import { DocumentFieldCategory, DocumentFieldValueType, DocumentTemplateType } from '@prisma/client';
import type { DocumentTemplateFieldResponse } from './types';

type CatalogField = DocumentTemplateFieldResponse & {
  supportedTypes: DocumentTemplateType[];
};

const ALL_TEMPLATE_TYPES: DocumentTemplateType[] = [
  DocumentTemplateType.INVOICE,
  DocumentTemplateType.PAYMENT_NOTICE,
  DocumentTemplateType.RECEIPT,
  DocumentTemplateType.CONTRACT,
  DocumentTemplateType.GENERAL_NOTICE,
  DocumentTemplateType.NOTICE,
  DocumentTemplateType.OTHER,
];

const BILLING_TEMPLATE_TYPES: DocumentTemplateType[] = [
  DocumentTemplateType.INVOICE,
  DocumentTemplateType.PAYMENT_NOTICE,
  DocumentTemplateType.RECEIPT,
];

const CATALOG: CatalogField[] = [
  {
    key: 'room.id',
    label: 'Room ID',
    category: DocumentFieldCategory.ROOM,
    valueType: DocumentFieldValueType.STRING,
    path: 'room.id',
    description: 'Internal room identifier.',
    sampleValue: 'room_3201',
    isRequired: true,
    isCollection: false,
    sortOrder: 10,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'room.number',
    label: 'Room Number',
    category: DocumentFieldCategory.ROOM,
    valueType: DocumentFieldValueType.STRING,
    path: 'room.number',
    description: 'Display room number.',
    sampleValue: '3201',
    isRequired: true,
    isCollection: false,
    sortOrder: 20,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'room.floorNumber',
    label: 'Floor Number',
    category: DocumentFieldCategory.ROOM,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'room.floorNumber',
    description: 'Floor that the room belongs to.',
    sampleValue: '3',
    isRequired: false,
    isCollection: false,
    sortOrder: 30,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'room.status',
    label: 'Room Status',
    category: DocumentFieldCategory.ROOM,
    valueType: DocumentFieldValueType.STRING,
    path: 'room.status',
    description: 'Current room occupancy status.',
    sampleValue: 'OCCUPIED',
    isRequired: false,
    isCollection: false,
    sortOrder: 40,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'tenant.fullName',
    label: 'Tenant Full Name',
    category: DocumentFieldCategory.TENANT,
    valueType: DocumentFieldValueType.STRING,
    path: 'tenant.fullName',
    description: 'Primary resident / contract holder display name.',
    sampleValue: 'Somchai Jaidee',
    isRequired: false,
    isCollection: false,
    sortOrder: 110,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'tenant.firstName',
    label: 'Tenant First Name',
    category: DocumentFieldCategory.TENANT,
    valueType: DocumentFieldValueType.STRING,
    path: 'tenant.firstName',
    description: 'Primary resident first name.',
    sampleValue: 'Somchai',
    isRequired: false,
    isCollection: false,
    sortOrder: 120,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'tenant.lastName',
    label: 'Tenant Last Name',
    category: DocumentFieldCategory.TENANT,
    valueType: DocumentFieldValueType.STRING,
    path: 'tenant.lastName',
    description: 'Primary resident last name.',
    sampleValue: 'Jaidee',
    isRequired: false,
    isCollection: false,
    sortOrder: 130,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'tenant.phone',
    label: 'Tenant Phone',
    category: DocumentFieldCategory.TENANT,
    valueType: DocumentFieldValueType.STRING,
    path: 'tenant.phone',
    description: 'Primary resident phone number.',
    sampleValue: '0891234567',
    isRequired: false,
    isCollection: false,
    sortOrder: 140,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'tenant.lineUserId',
    label: 'Tenant LINE User ID',
    category: DocumentFieldCategory.TENANT,
    valueType: DocumentFieldValueType.STRING,
    path: 'tenant.lineUserId',
    description: 'Linked LINE user identifier.',
    sampleValue: 'U1234567890',
    isRequired: false,
    isCollection: false,
    sortOrder: 150,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'contract.startDate',
    label: 'Contract Start Date',
    category: DocumentFieldCategory.CONTRACT,
    valueType: DocumentFieldValueType.DATE,
    path: 'contract.startDate',
    description: 'Contract start date.',
    sampleValue: '2026-01-01',
    isRequired: false,
    isCollection: false,
    sortOrder: 210,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'contract.endDate',
    label: 'Contract End Date',
    category: DocumentFieldCategory.CONTRACT,
    valueType: DocumentFieldValueType.DATE,
    path: 'contract.endDate',
    description: 'Contract end date.',
    sampleValue: '2026-12-31',
    isRequired: false,
    isCollection: false,
    sortOrder: 220,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'contract.monthlyRent',
    label: 'Contract Monthly Rent',
    category: DocumentFieldCategory.CONTRACT,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'contract.monthlyRent',
    description: 'Contract monthly rent snapshot.',
    sampleValue: '2900',
    isRequired: false,
    isCollection: false,
    sortOrder: 230,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'billing.recordId',
    label: 'Billing Record ID',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.STRING,
    path: 'billing.recordId',
    description: 'Billing record for the selected month.',
    sampleValue: 'billing_2026_12_3201',
    isRequired: false,
    isCollection: false,
    sortOrder: 310,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.year',
    label: 'Billing Year',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.year',
    description: 'Billing year.',
    sampleValue: '2026',
    isRequired: false,
    isCollection: false,
    sortOrder: 320,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.month',
    label: 'Billing Month',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.month',
    description: 'Billing month number.',
    sampleValue: '12',
    isRequired: false,
    isCollection: false,
    sortOrder: 330,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.subtotal',
    label: 'Billing Subtotal',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.subtotal',
    description: 'Subtotal from billing record.',
    sampleValue: '3696',
    isRequired: false,
    isCollection: false,
    sortOrder: 340,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.total',
    label: 'Billing Total',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.total',
    description: 'Final total from billing record.',
    sampleValue: '3696',
    isRequired: false,
    isCollection: false,
    sortOrder: 350,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.rentAmount',
    label: 'Room Rent Amount',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.rentAmount',
    description: 'Room rent from billing record.',
    sampleValue: '2900',
    isRequired: false,
    isCollection: false,
    sortOrder: 352,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.waterUnits',
    label: 'Water Units (kL)',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.waterUnits',
    description: 'Water consumption in units.',
    sampleValue: '15',
    isRequired: false,
    isCollection: false,
    sortOrder: 360,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.waterUsageCharge',
    label: 'Water Usage Charge',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.waterUsageCharge',
    description: 'Water usage charge amount.',
    sampleValue: '300',
    isRequired: false,
    isCollection: false,
    sortOrder: 362,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.waterServiceFee',
    label: 'Water Service Fee',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.waterServiceFee',
    description: 'Water service fee.',
    sampleValue: '30',
    isRequired: false,
    isCollection: false,
    sortOrder: 364,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.waterTotal',
    label: 'Water Total',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.waterTotal',
    description: 'Total water bill.',
    sampleValue: '330',
    isRequired: false,
    isCollection: false,
    sortOrder: 366,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.waterPrev',
    label: 'Water Previous Reading',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.waterPrev',
    description: 'Previous water meter reading.',
    sampleValue: '1200',
    isRequired: false,
    isCollection: false,
    sortOrder: 367,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.waterCurr',
    label: 'Water Current Reading',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.waterCurr',
    description: 'Current water meter reading.',
    sampleValue: '1215',
    isRequired: false,
    isCollection: false,
    sortOrder: 368,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.electricUnits',
    label: 'Electric Units (kWh)',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.electricUnits',
    description: 'Electricity consumption in kWh.',
    sampleValue: '250',
    isRequired: false,
    isCollection: false,
    sortOrder: 370,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.electricUsageCharge',
    label: 'Electric Usage Charge',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.electricUsageCharge',
    description: 'Electricity usage charge amount.',
    sampleValue: '996',
    isRequired: false,
    isCollection: false,
    sortOrder: 372,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.electricServiceFee',
    label: 'Electric Service Fee',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.electricServiceFee',
    description: 'Electricity service fee.',
    sampleValue: '300',
    isRequired: false,
    isCollection: false,
    sortOrder: 374,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.electricTotal',
    label: 'Electric Total',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.electricTotal',
    description: 'Total electric bill.',
    sampleValue: '1296',
    isRequired: false,
    isCollection: false,
    sortOrder: 376,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.electricPrev',
    label: 'Electric Previous Reading',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.electricPrev',
    description: 'Previous electric meter reading.',
    sampleValue: '5000',
    isRequired: false,
    isCollection: false,
    sortOrder: 377,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.electricCurr',
    label: 'Electric Current Reading',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.NUMBER,
    path: 'billing.electricCurr',
    description: 'Current electric meter reading.',
    sampleValue: '5250',
    isRequired: false,
    isCollection: false,
    sortOrder: 378,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.furnitureFee',
    label: 'Furniture Fee',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.furnitureFee',
    description: 'Furniture fee from billing record.',
    sampleValue: '0',
    isRequired: false,
    isCollection: false,
    sortOrder: 380,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.otherFee',
    label: 'Other Fee',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'billing.otherFee',
    description: 'Other fees from billing record.',
    sampleValue: '0',
    isRequired: false,
    isCollection: false,
    sortOrder: 382,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.dueDate',
    label: 'Billing Due Date',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.DATE,
    path: 'billing.dueDate',
    description: 'Calculated due date for billing.',
    sampleValue: '2026-12-05',
    isRequired: false,
    isCollection: false,
    sortOrder: 360,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.status',
    label: 'Billing Status',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.STRING,
    path: 'billing.status',
    description: 'Billing record status.',
    sampleValue: 'INVOICED',
    isRequired: false,
    isCollection: false,
    sortOrder: 370,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.invoiceNumber',
    label: 'Invoice Number',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.STRING,
    path: 'billing.invoiceNumber',
    description: 'Latest invoice number for the billing record.',
    sampleValue: 'INV-2026-12-3201-ABC123',
    isRequired: false,
    isCollection: false,
    sortOrder: 380,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing.invoiceStatus',
    label: 'Invoice Status',
    category: DocumentFieldCategory.BILLING,
    valueType: DocumentFieldValueType.STRING,
    path: 'billing.invoiceStatus',
    description: 'Latest invoice status for the billing record.',
    sampleValue: 'GENERATED',
    isRequired: false,
    isCollection: false,
    sortOrder: 390,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'billing_items',
    label: 'Billing Line Items',
    category: DocumentFieldCategory.BILLING_ITEM,
    valueType: DocumentFieldValueType.ARRAY,
    path: 'billingItems',
    description: 'Repeat collection for billing items.',
    sampleValue: null,
    isRequired: false,
    isCollection: true,
    sortOrder: 410,
    supportedTypes: BILLING_TEMPLATE_TYPES,
    metadata: {
      itemFields: ['typeName', 'description', 'quantity', 'unitPrice', 'amount', 'amountFormatted'],
    },
  },
  {
    key: 'payment.status',
    label: 'Payment Status',
    category: DocumentFieldCategory.PAYMENT,
    valueType: DocumentFieldValueType.STRING,
    path: 'payment.status',
    description: 'Matched payment state for the billing month.',
    sampleValue: 'PENDING',
    isRequired: false,
    isCollection: false,
    sortOrder: 510,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'payment.lastPaidAt',
    label: 'Last Payment Date',
    category: DocumentFieldCategory.PAYMENT,
    valueType: DocumentFieldValueType.DATE,
    path: 'payment.lastPaidAt',
    description: 'Last confirmed payment date for the invoice.',
    sampleValue: '2026-12-02',
    isRequired: false,
    isCollection: false,
    sortOrder: 520,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'payment.totalConfirmed',
    label: 'Confirmed Payment Amount',
    category: DocumentFieldCategory.PAYMENT,
    valueType: DocumentFieldValueType.CURRENCY,
    path: 'payment.totalConfirmed',
    description: 'Total confirmed payment matched to the invoice.',
    sampleValue: '3696',
    isRequired: false,
    isCollection: false,
    sortOrder: 530,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'apartment.name',
    label: 'Apartment Name',
    category: DocumentFieldCategory.APARTMENT,
    valueType: DocumentFieldValueType.STRING,
    path: 'apartment.name',
    description: 'Building name from configuration.',
    sampleValue: 'Apartment ERP Residence',
    isRequired: true,
    isCollection: false,
    sortOrder: 610,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'apartment.address',
    label: 'Apartment Address',
    category: DocumentFieldCategory.APARTMENT,
    valueType: DocumentFieldValueType.STRING,
    path: 'apartment.address',
    description: 'Building address block.',
    sampleValue: '123 Demo Road, Bangkok',
    isRequired: false,
    isCollection: false,
    sortOrder: 620,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'system.generatedAt',
    label: 'Generated At',
    category: DocumentFieldCategory.SYSTEM,
    valueType: DocumentFieldValueType.DATE,
    path: 'system.generatedAt',
    description: 'Timestamp when the document is generated.',
    sampleValue: '2026-12-01T08:00:00Z',
    isRequired: true,
    isCollection: false,
    sortOrder: 710,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'computed.billingMonthLabel',
    label: 'Billing Month Label',
    category: DocumentFieldCategory.COMPUTED,
    valueType: DocumentFieldValueType.STRING,
    path: 'computed.billingMonthLabel',
    description: 'Formatted month label, e.g. December 2026.',
    sampleValue: 'December 2026',
    isRequired: false,
    isCollection: false,
    sortOrder: 810,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'computed.dueDateLabel',
    label: 'Due Date Label',
    category: DocumentFieldCategory.COMPUTED,
    valueType: DocumentFieldValueType.STRING,
    path: 'computed.dueDateLabel',
    description: 'Human-friendly due date label.',
    sampleValue: '05 December 2026',
    isRequired: false,
    isCollection: false,
    sortOrder: 820,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
  {
    key: 'computed.occupancyDisplay',
    label: 'Occupancy Display',
    category: DocumentFieldCategory.COMPUTED,
    valueType: DocumentFieldValueType.STRING,
    path: 'computed.occupancyDisplay',
    description: 'Display string for room occupants.',
    sampleValue: 'Somchai Jaidee (Primary)',
    isRequired: false,
    isCollection: false,
    sortOrder: 830,
    supportedTypes: ALL_TEMPLATE_TYPES,
  },
  {
    key: 'computed.totalAmountFormatted',
    label: 'Formatted Total Amount',
    category: DocumentFieldCategory.COMPUTED,
    valueType: DocumentFieldValueType.STRING,
    path: 'computed.totalAmountFormatted',
    description: 'Currency formatted total amount.',
    sampleValue: 'THB 3,696.00',
    isRequired: false,
    isCollection: false,
    sortOrder: 840,
    supportedTypes: BILLING_TEMPLATE_TYPES,
  },
];

export function getTemplateFieldCatalog(type: DocumentTemplateType): DocumentTemplateFieldResponse[] {
  return CATALOG
    .filter((field) => field.supportedTypes.includes(type))
    .map((field) => ({
      key: field.key,
      label: field.label,
      category: field.category,
      valueType: field.valueType,
      path: field.path,
      description: field.description,
      sampleValue: field.sampleValue,
      isRequired: field.isRequired,
      isCollection: field.isCollection,
      sortOrder: field.sortOrder,
      metadata: field.metadata,
    }));
}

export function getTemplateFieldCatalogByCategory(type: DocumentTemplateType): Record<string, DocumentTemplateFieldResponse[]> {
  return getTemplateFieldCatalog(type).reduce<Record<string, DocumentTemplateFieldResponse[]>>((acc, field) => {
    const key = field.category.toLowerCase();
    if (!acc[key]) {
      acc[key] = [];
    }
    acc[key].push(field);
    return acc;
  }, {});
}

function escapeAttribute(value: string): string {
  return value.replace(/"/g, '&quot;');
}

export function createScalarFieldMarkup(fieldKey: string, label?: string): string {
  const safeLabel = escapeAttribute(label ?? fieldKey);
  return `<span data-template-field="${escapeAttribute(fieldKey)}" data-template-label="${safeLabel}">{{${fieldKey}}}</span>`;
}

export function createRepeatBlockMarkup(collectionKey: string): string {
  if (collectionKey !== 'billing_items') {
    return `<div data-template-repeat="${escapeAttribute(collectionKey)}"><p data-template-field="label">{{label}}</p></div>`;
  }

  return [
    '<table>',
    '  <thead>',
    '    <tr>',
    '      <th>Item</th>',
    '      <th>Qty</th>',
    '      <th>Unit Price</th>',
    '      <th>Amount</th>',
    '    </tr>',
    '  </thead>',
    '  <tbody data-template-repeat="billing_items">',
    '    <tr>',
    '      <td><span data-template-field="typeName">{{billing_items.typeName}}</span></td>',
    '      <td><span data-template-field="quantity">{{billing_items.quantity}}</span></td>',
    '      <td><span data-template-field="unitPrice">{{billing_items.unitPrice}}</span></td>',
    '      <td><span data-template-field="amountFormatted">{{billing_items.amountFormatted}}</span></td>',
    '    </tr>',
    '  </tbody>',
    '</table>',
  ].join('\n');
}
