/**
 * Seed proper starter content for existing templates
 */
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const TEMPLATES = {
  INVOICE: {
    name: 'ใบแจ้งหนี้รายเดือน',
    subject: 'ใบแจ้งหนี้ค่าเช่าห้องพัก ห้อง {{room.number}}',
    body: `<!--template-meta:{"pageSize":"A4","orientation":"PORTRAIT","marginPreset":"normal","fontFamily":"sarabun","fontSize":"base","lineHeight":"relaxed"}-->
<header data-template-region="header">
<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px;">
  <div>
    <div style="font-size:22px;font-weight:700;color:#1c3860;">บริษัท อพาร์ตเมนต์ แมนเนจเม้นท์ จำกัด</div>
    <div style="font-size:12px;color:#666;margin-top:2px;">123 ถนนสุขุมวิท แขวงคลองเตา เขตบางนา กรุงเทพฯ 10260</div>
    <div style="font-size:12px;color:#666;">โทร. 02-xxx-xxxx | Tax ID: 010554xxxxxxx</div>
  </div>
  <div style="text-align:right;">
    <div style="font-size:13px;color:#888;">ใบแจ้งหนี้</div>
    <div style="font-size:20px;font-weight:700;color:#1c3860;margin-top:4px;">INV-{{invoice.year}}{{invoice.monthStr}}</div>
    <div style="font-size:12px;color:#666;margin-top:4px;">วันที่: {{invoice.issueDateStr}}</div>
    <div style="font-size:12px;color:#666;">กำหนดชำระ: {{invoice.dueDateStr}}</div>
  </div>
</div>
<hr style="border:none;border-top:1.5px solid #1c3860;margin:8px 0;"/>
</header>
<section data-template-region="body">
<div style="margin-bottom:16px;">
  <div style="font-size:14px;line-height:1.8;">
    <strong>เรียน คุณ{{tenant.fullName}}</strong> &nbsp;|&nbsp; ห้อง <strong>{{room.number}}</strong>
  </div>
  <div style="font-size:13px;color:#555;margin-top:4px;">
    ที่อยู่: {{tenant.address}}
  </div>
</div>

<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:12px 16px;margin-bottom:16px;">
  <div style="font-size:13px;font-weight:600;color:#1c3860;margin-bottom:8px;">รายละเอียดค่าใช้บริการประจำเดือน {{invoice.monthStr}}/{{invoice.year}}</div>
  <table style="width:100%;font-size:13px;border-collapse:collapse;">
    <tr style="background:#e8f0fe;">
      <td style="padding:6px 10px;font-weight:600;color:#1c3860;">รายการ</td>
      <td style="padding:6px 10px;text-align:right;font-weight:600;color:#1c3860;">จำนวนเงิน (บาท)</td>
    </tr>
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าเช่าห้องพัก</td>
      <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{billing.rentAmount}}</td>
    </tr>
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าน้ำประปา</td>
      <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{billing.waterAmount}}</td>
    </tr>
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าไฟฟ้า</td>
      <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{billing.electricAmount}}</td>
    </tr>
    {{#if billing.furnitureAmount}}
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าเฟอร์นิเจอร์</td>
      <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{billing.furnitureAmount}}</td>
    </tr>
    {{/if}}
    {{#if billing.otherAmount}}
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">รายการอื่น</td>
      <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{billing.otherAmount}}</td>
    </tr>
    {{/if}}
    <tr style="background:#1c3860;color:white;">
      <td style="padding:8px 10px;font-weight:700;">รวมทั้งสิ้น</td>
      <td style="padding:8px 10px;text-align:right;font-weight:700;">{{billing.totalDue}}</td>
    </tr>
  </table>
</div>

<div style="margin-bottom:16px;font-size:13px;line-height:1.7;color:#333;">
  <strong>วิธีการชำระเงิน:</strong><br/>
  • ชำระด้วยเงินสด ณ สำนักงาน<br/>
  • โอนเงินเข้าบัญชี ธนาคารกสิกรไทย สาขาบางนา เลขที่บัญชี <strong>123-456-7890</strong> ชื่อบัญชี "บริษัท อพาร์ตเมนต์ แมนเนจเม้นท์ จำกัด"<br/>
  • สแกน QR Code ที่ด้านล่างของใบแจ้งหนี้
</div>

<div style="background:#fff3cd;border:1.5px solid #f29d21;border-radius:8px;padding:10px 14px;font-size:12px;color:#8b5e00;margin-bottom:12px;">
  ⚠️ <strong>หมายเหตุ:</strong> กรุณาชำระเงินภายในวันที่ {{invoice.dueDateStr}} มิฉะนั้นจะมีค่าปรับตามสัญญาเช่า
</div>
</section>
<footer data-template-region="footer">
<hr style="border:none;border-top:1px solid #e2e8f0;margin:8px 0 6px;"/>
<div style="display:flex;justify-content:space-between;font-size:11px;color:#888;">
  <span>Generated by Apartment ERP</span>
  <span>หน้า {{pageNum}} / {{totalPages}}</span>
</div>
</footer>`
  },
  PAYMENT_NOTICE: {
    name: 'แจ้งชำระค่าบริการ',
    subject: 'แจ้งชำระค่าบริการ ประจำเดือน {{invoice.monthStr}}/{{invoice.year}}',
    body: `<!--template-meta:{"pageSize":"A4","orientation":"PORTRAIT","marginPreset":"normal","fontFamily":"sarabun","fontSize":"base","lineHeight":"relaxed"}-->
<header data-template-region="header">
<div style="background:#1c3860;color:white;padding:16px 24px;border-radius:8px 8px 0 0;">
  <div style="font-size:18px;font-weight:700;">แจ้งชำระค่าบริการ</div>
  <div style="font-size:13px;opacity:0.85;margin-top:4px;">ประจำเดือน {{invoice.monthStr}}/{{invoice.year}}</div>
</div>
</header>
<section data-template-region="body">
<div style="margin:20px 0;font-size:14px;line-height:1.8;">
  <p>เรียน คุณ<span data-template-field="tenantName" data-template-label="ชื่อผู้เช่า">{{tenant.fullName}}</span> ห้องพัก <strong>{{room.number}}</strong></p>
  <p style="margin-top:12px;">ตามที่ท่านได้ทำสัญญาเช่าห้องพักกับทางเรานั้น บัดนี้ถึงกำหนดชำระค่าเช่าประจำเดือน <strong>{{invoice.monthStr}}/{{invoice.year}}</strong> แล้ว จึงเรียนแจ้งให้ท่านทราบ</p>
</div>

<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0;">
  <div style="font-size:15px;font-weight:700;color:#1c3860;margin-bottom:12px;">สรุปยอดค้างชำระ</div>
  <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px dashed #ddd;font-size:14px;">
    <span>ค่าเช่าห้อง</span><strong>{{billing.rentAmount}} บาท</strong>
  </div>
  <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px dashed #ddd;font-size:14px;">
    <span>ค่าน้ำ</span><strong>{{billing.waterAmount}} บาท</strong>
  </div>
  <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px dashed #ddd;font-size:14px;">
    <span>ค่าไฟฟ้า</span><strong>{{billing.electricAmount}} บาท</strong>
  </div>
  <div style="display:flex;justify-content:space-between;padding:10px 0;font-size:16px;font-weight:700;color:#1c3860;background:#e8f0fe;padding:10px 12px;border-radius:6px;margin-top:8px;">
    <span>รวมทั้งสิ้น</span><span>{{billing.totalDue}} บาท</span>
  </div>
</div>

<div style="background:#fef2f2;border:1.5px solid #ef4444;border-radius:8px;padding:12px 16px;color:#991b1b;font-size:13px;">
  ⚠️ กรุณาชำระเงินภายในวันที่ <strong>{{invoice.dueDateStr}}</strong> มิฉะนั้นจะมีผลตามสัญญาเช่า
</div>

<div style="margin-top:20px;font-size:13px;color:#555;">
  <strong>สอบถามเพิ่มเติม:</strong> โทร. 02-xxx-xxxx ต่อ 1 (แผนกบัญชี)
</div>
</section>
<footer data-template-region="footer">
<div style="font-size:11px;color:#888;text-align:center;margin-top:8px;">
  บริษัท อพาร์ตเมนต์ แมนเนจเม้นท์ จำกัด | โทร. 02-xxx-xxxx | www.apartment.co.th
</div>
</footer>`
  },
  RECEIPT: {
    name: 'ใบเสร็จรับเงิน',
    subject: 'ใบเสร็จรับเงิน ชำระค่าเช่าห้อง {{room.number}}',
    body: `<!--template-meta:{"pageSize":"A4","orientation":"PORTRAIT","marginPreset":"normal","fontFamily":"sarabun","fontSize":"base","lineHeight":"relaxed"}-->
<header data-template-region="header">
<div style="background:#1c3860;color:white;padding:20px 24px;text-align:center;border-radius:8px 8px 0 0;">
  <div style="font-size:22px;font-weight:700;">ใบเสร็จรับเงิน</div>
  <div style="font-size:14px;opacity:0.9;margin-top:4px;">RECEIPT</div>
</div>
</header>
<section data-template-region="body">
<div style="display:flex;gap:0;align-items:stretch;margin:20px 0;">
  <div style="flex:1;background:#f8fafc;border:2px solid #1c3860;border-right:none;border-radius:8px 0 0 8px;padding:16px 20px;">
    <div style="font-size:12px;color:#888;margin-bottom:8px;">รับเงินจาก / Received from</div>
    <div style="font-size:15px;font-weight:600;color:#1c3860;margin-bottom:6px;">{{tenant.fullName}}</div>
    <div style="font-size:13px;color:#555;">ห้อง: <strong>{{room.number}}</strong></div>
    <div style="font-size:13px;color:#555;margin-top:4px;">วันที่รับ: {{payment.dateStr}}</div>
  </div>
  <div style="background:#1c3860;color:white;border-radius:0 8px 8px 0;border:2px solid #1c3860;padding:20px 28px;display:flex;flex-direction:column;justify-content:center;align-items:center;min-width:180px;text-align:center;">
    <div style="font-size:11px;color:#f29d21;font-weight:600;">จำนวนเงิน (บาท)</div>
    <div style="font-size:28px;font-weight:700;margin-top:4px;">{{payment.amount}}</div>
    <div style="font-size:12px;opacity:0.8;margin-top:4px;">BAHT</div>
  </div>
</div>

<div style="background:#f0fdf4;border:1.5px solid #22c55e;border-radius:8px;padding:12px 16px;margin-bottom:16px;font-size:13px;color:#166534;">
  ✓ ชำระเงินเรียบร้อยแล้ว
</div>

<table style="width:100%;font-size:13px;border-collapse:collapse;margin-bottom:16px;">
  <tr style="background:#e8f0fe;">
    <td style="padding:6px 10px;font-weight:600;color:#1c3860;">รายการ</td>
    <td style="padding:6px 10px;text-align:right;font-weight:600;color:#1c3860;">จำนวนเงิน</td>
  </tr>
  <tr>
    <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าเช่าห้องพัก เดือน {{invoice.monthStr}}/{{invoice.year}}</td>
    <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{billing.rentAmount}}</td>
  </tr>
  {{#if payment.waterAmount}}
  <tr>
    <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าน้ำ</td>
    <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{payment.waterAmount}}</td>
  </tr>
  {{/if}}
  {{#if payment.electricAmount}}
  <tr>
    <td style="padding:6px 10px;border-bottom:1px solid #e2e8f0;">ค่าไฟฟ้า</td>
    <td style="padding:6px 10px;text-align:right;border-bottom:1px solid #e2e8f0;">{{payment.electricAmount}}</td>
  </tr>
  {{/if}}
  <tr style="background:#1c3860;color:white;">
    <td style="padding:8px 10px;font-weight:700;">รวม</td>
    <td style="padding:8px 10px;text-align:right;font-weight:700;">{{payment.amount}}</td>
  </tr>
</table>

<div style="font-size:13px;color:#555;margin-top:12px;">
  <strong>วิธีชำระ:</strong> {{payment.method}}<br/>
  <strong>หลักฐาน:</strong> {{payment.reference}}
</div>
</section>
<footer data-template-region="footer">
<div style="text-align:center;font-size:11px;color:#888;margin-top:8px;">
  บริษัท อพาร์ตเมนต์ แมนเนจเม้นท์ จำกัด | โทร. 02-xxx-xxxx
</div>
</footer>`
  },
  CONTRACT: {
    name: 'สัญญาเช่าที่พัก',
    subject: 'สัญญาเช่าที่พักอาศัย ห้อง {{room.number}}',
    body: `<!--template-meta:{"pageSize":"A4","orientation":"PORTRAIT","marginPreset":"normal","fontFamily":"sarabun","fontSize":"base","lineHeight":"relaxed"}-->
<header data-template-region="header">
<div style="text-align:center;padding:16px 0;border-bottom:2px solid #1c3860;">
  <div style="font-size:20px;font-weight:700;color:#1c3860;">สัญญาเช่าที่พักอาศัย</div>
  <div style="font-size:13px;color:#888;margin-top:4px;">RENTAL AGREEMENT</div>
</div>
</header>
<section data-template-region="body">
<div style="margin:16px 0;font-size:13px;line-height:1.8;">
  <p style="text-indent:2em;">สัญญาเช่านี้ทำขึ้น ณ บริษัท อพาร์ตเมนต์ แมนเนจเม้นท์ จำกัด เลขที่ 123 ถนนสุขุมวิท กรุงเทพฯ ในวันที่ <strong>{{contract.signDateStr}}</strong></p>
  <p style="text-indent:2em;margin-top:12px;">ระหว่าง <strong>บริษัท อพาร์ตเมนต์ แมนเนจเม้นท์ จำกัด</strong> ในฐานะผู้ให้เช่า กับ <strong>คุณ{{tenant.fullName}}</strong> ในฐานะผู้เช่า โดยมีข้อสำคัญดังต่อไปนี้:</p>
</div>

<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin:16px 0;font-size:13px;line-height:1.8;">
  <div style="font-size:14px;font-weight:700;color:#1c3860;margin-bottom:10px;">1. รายละเอียดผู้เช่า</div>
  <div style="display:grid;grid-template-columns:120px 1fr;gap:6px;">
    <span style="color:#888;">ชื่อ-นามสกุล:</span><strong>{{tenant.fullName}}</strong>
    <span style="color:#888;">เลขบัตรประจำตัว:</span><span>{{tenant.idCardNo}}</span>
    <span style="color:#888;">โทรศัพท์:</span><span>{{tenant.phone}}</span>
    <span style="color:#888;">ห้องพัก:</span><strong>{{room.number}}</strong>
    <span style="color:#888;">ชั้น:</span><span>{{room.floorNo}}</span>
  </div>
</div>

<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin:16px 0;font-size:13px;line-height:1.8;">
  <div style="font-size:14px;font-weight:700;color:#1c3860;margin-bottom:10px;">2. ค่าเช่าและระยะเวลา</div>
  <div style="display:grid;grid-template-columns:120px 1fr;gap:6px;">
    <span style="color:#888;">ค่าเช่ารายเดือน:</span><strong>{{contract.monthlyRent}} บาท</strong>
    <span style="color:#888;">เงินประกัน:</span><span>{{contract.deposit}} บาท</span>
    <span style="color:#888;">วันที่เริ่มเช่า:</span><strong>{{contract.startDateStr}}</strong>
    <span style="color:#888;">วันสิ้นสุด:</span><strong>{{contract.endDateStr}}</strong>
    <span style="color:#888;">ระยะเวลา:</span><span>{{contract.duration}} เดือน</span>
  </div>
</div>

<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin:16px 0;font-size:13px;line-height:1.8;">
  <div style="font-size:14px;font-weight:700;color:#1c3860;margin-bottom:10px;">3. สิ่งอำนวยความสะดวก</div>
  <div style="display:grid;grid-template-columns:120px 1fr;gap:6px;">
    <span style="color:#888;">เฟอร์นิเจอร์:</span><span>{{room.hasFurniture ? 'มี' : 'ไม่มี'}}</span>
    <span style="color:#888;">ค่าเฟอร์นิเจอร์:</span><span>{{room.furnitureAmount || '-'}} บาท/เดือน</span>
  </div>
</div>

<div style="margin:16px 0;font-size:13px;line-height:1.8;">
  <p style="text-indent:2em;"><strong>4. การชำระค่าเช่า:</strong> ผู้เช่าตกลงชำระค่าเช่าทุกวันที่ 5 ของเดือน โดยโอนเข้าบัญชีธนาคารกสิกรไทย เลขที่ 123-456-7890</p>
  <p style="text-indent:2em;margin-top:8px;"><strong>5. สัญญาบอกเลิก:</strong> ฝ่ายใดฝ่ายหนึ่งต้องแจ้งเป็นลายลักษณ์อักษรล่วงหน้า 30 วัน</p>
</div>
</section>
<footer data-template-region="footer">
<div style="display:flex;justify-content:space-between;margin-top:24px;font-size:12px;">
  <div style="text-align:center;">
    <div style="height:40px;"></div>
    <div style="border-top:1px solid #333;padding-top:4px;">ผู้ให้เช่า</div>
  </div>
  <div style="text-align:center;">
    <div style="height:40px;"></div>
    <div style="border-top:1px solid #333;padding-top:4px;">ผู้เช่า</div>
  </div>
</div>
<div style="font-size:10px;color:#aaa;text-align:center;margin-top:16px;">
  สร้างโดย Apartment ERP | หน้า {{pageNum}}/{{totalPages}}
</div>
</footer>`
  }
};

async function seedStarterContent() {
  console.log('=== Seeding starter content for templates ===\n');

  for (const [type, data] of Object.entries(TEMPLATES)) {
    console.log(`Processing ${type}...`);

    const template = await prisma.documentTemplate.findFirst({ where: { type } });
    if (!template) {
      console.log(`  ${type}: not found, skipping`);
      continue;
    }

    // Update template body
    await prisma.documentTemplate.update({
      where: { id: template.id },
      data: { subject: data.subject, body: data.body }
    });

    // Update active version content
    const activeVersion = await prisma.documentTemplateVersion.findFirst({
      where: { templateId: template.id, status: 'ACTIVE' }
    });

    if (activeVersion) {
      await prisma.documentTemplateVersion.update({
        where: { id: activeVersion.id },
        data: { subject: data.subject, body: data.body }
      });
      console.log(`  ${type}: Updated template body + version content`);
    } else {
      console.log(`  ${type}: No active version found`);
    }
  }

  console.log('\nDone!');
  await prisma.$disconnect();
}

seedStarterContent().catch(e => { console.error(e); process.exit(1); });